name: Terraform CI/CD

on:
  push:

  pull_request:
    branches: [ dev ]
    types: [ opened, synchronize, reopened, closed ]

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: env/dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::914690098914:role/github-terraform-service-role
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -no-color -out=tfplan

    - name: Save Plan to File
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      run: terraform show -no-color tfplan > plan.txt

    - name: Comment Plan in PR
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: plan.txt

    - name: Terraform Apply
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: terraform apply -auto-approve tfplan